### ISSUE TITLE
blog:  "2015-10-28: Why Vue.js doesn't support templateURL" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#1]
下記のブログ記事の翻訳。

https://github.com/vuejs/vuejs.org/commit/1f3841b3809e4876d4ae0aeecfc30de9c78ea078

**Comment by hashrock** [comment]
やりたいです！:hand:

**Comment by kazupon** [comment]
ありがとうございます！
よろしくお願いします！ :smile_cat:

**Comment by kazupon** [comment]
Merge https://github.com/vuejs/jp.vuejs.org/pull/88
