### ISSUE TITLE
[Cookbook]: Client-Side Storageの翻訳 

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#1017]
## 原文
https://vuejs.org/v2/cookbook/client-side-storage.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/client-side-storage.md

**Comment by nicedaichi3** [comment]
こちらいただいても良いですか？

**Comment by kazupon** [comment]
@nicedchy 
よろしくお願いします！ 🙏

**Comment by nicedaichi3** [comment]
@kazupon 
すいません、本業のほうが忙しくなかなか作業時間とれず
もう少しかかりそうです 🙇

**Comment by kazupon** [comment]
@nicedchy 
大丈夫です！

**Comment by kazupon** [comment]
マージしたのでclose
