### ISSUE TITLE
[Cookbook]: Packaging Vue Components for npm の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#1033]
## 原文
https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/packaging-sfc-for-npm.md

**Comment by desigrammer** [comment]
こちらやらせて頂いてもよろしいでしょうか。

**Comment by kazupon** [comment]
@desigrammer 
ありがとうございます！
はい、お願いします！

**Comment by desigrammer** [comment]
ありがとうございます。来週までには終わるかと思います。

WIP の PR を立てて小セクションごとに翻訳し、随時コミットしていく形で進めてよろしいでしょうか。
一つのファイルに複数のコミットが発生させないようにしたり、
即マージできない PR を作らない方針が有りましたら教えていただけると嬉しいです。

**Comment by kazupon** [comment]
全然大丈夫です。どちらかというと、一気にレビューするのは重いので、WIPのPRの方が助かります。:pray: 
途中でいろいろ指摘できるのと、段階的に見ること(レビュー)ができますので。

**Comment by desigrammer** [comment]
WIP の PR を作成させていただきました。

もう一つ伺いたいのですが PR 元になっているブランチ( desigrammer:issue_1033 )にコミットをプッシュした後、
レビューのお願いを同 PR もしくは本 issue にコメントしていった方がよろしいでしょうか。
一々通知されるのをご面倒に感じないかと思っての質問になります。

**Comment by desigrammer** [comment]
一通りの作業が完了しましたので WIP を外しました。#1038 のレビューをお願いしてもよろしいでしょうか。

**Comment by kazupon** [comment]
close #1038 due to merged
