### ISSUE TITLE
support vue.js development の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#104]
下記ページの翻訳
http://vuejs.org/support-vuejs/

ソース
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/support-vuejs/index.md

**Comment by BYODKM** [comment]
今晩PRしますね

**Comment by BYODKM** [comment]
@kazupon PRしました #105

**Comment by kazupon** [comment]
ありがとうございました！
