### ISSUE TITLE
 comparison note about react-like librariesの翻訳

### ISSUE THREAD

**Issue by ysgk** [vuejs/jp.vuejs.org#1061]
初めまして。最近Vue.jsを触り始めたものです。

「他のフレームワークとの比較」ページで未翻訳となっている Preact-and-Other-React-Like-Libraries の章を翻訳しても構いませんか？

該当箇所
https://jp.vuejs.org/v2/guide/comparison.html#Preact-and-Other-React-Like-Libraries

関連
https://github.com/vuejs/jp.vuejs.org/pull/1002

**Comment by kazupon** [comment]
@ysgk はい、よろしくお願いします！ 🙏
