### ISSUE TITLE
[Cookbook]: Dockerize Vue.js Appの翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#1086]
## 原文
https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/dockerize-vuejs-app.md

**Comment by resessh** [comment]
やりたいです！ ✋

**Comment by kazupon** [comment]
@resessh 
早速ありがとうございます！
では、よろしくお願いします！
