### ISSUE TITLE
Upgrade to husky v1.0

### ISSUE THREAD

**Issue by potato4d** [vuejs/jp.vuejs.org#1224]
## About

husky が正式バージョンがリリースされ、インターフェースに破壊的変更があったので追従したい。

https://github.com/typicode/husky/blob/master/CHANGELOG.md#100

**Comment by kubosho** [comment]
そもそもの話になりますが、huskyをインストールしている理由はなんでしょうか？

huskyで実現していること(コミット前のlint)は、lintをCIでおこなっているので、CIでやっているならhuskyがなくても問題ないと思います。

**Comment by potato4d** [comment]
@kubosho

元々の理由としては私が入れたのではないので答えられませんが、実際の効果としては、翻訳自体には興味あってもCIやLintに詳しくない人がある程度Validな状態でコミットしてくれることに役立っていますね。

Vue.jsは特にWeb制作のシーンでの利用なども多く、Lint/CIに馴染みのない人も多いので、 npm installをしていない場合はどうしても通ってしまうことはありますが、可能な限り「CI落ちてるので治してください🙏」が起こらないようになっている感覚値はあります。

**Comment by kubosho** [comment]
なるほど、納得です。

**Comment by re-fort** [comment]
huskyは自分が入れました。
その時はPRを作ってもらったもののlint errorで落ちてるケースなどがたまにあって、それを治してもらうために発生するコミュニケーションをなくすためで導入しました。

いまは全ファイルを走査対象にしてしまっているので、commit対象のファイルだけを対象にするってのはしたいですねー...

**Comment by kubosho** [comment]
commit対象のファイルだけを対象にする件は別問題っぽいのでissue作っておきました 🙌

**Comment by re-fort** [comment]
@kubosho ありがとうございます！:blush:
