### ISSUE TITLE
huskyでcommit対象のファイルだけを対象にする

### ISSUE THREAD

**Issue by kubosho** [vuejs/jp.vuejs.org#1225]
refs: https://github.com/vuejs/jp.vuejs.org/issues/1224#issuecomment-424744826

**Comment by potato4d** [comment]
https://github.com/okonet/lint-staged を使うと良いだろうか

**Comment by re-fort** [comment]
pre-commitではstagedなファイルを対象、CIは現状のままがいいかなーと思います
