### ISSUE TITLE
package-lock.json または yarn.lock どちらかに一本化したい

### ISSUE THREAD

**Issue by kubosho** [vuejs/jp.vuejs.org#1230]
パッケージ更新のときにどちらも更新する必要があって大変そうなのと、もしかしたらパッケージ依存解決のロジックが違って依存パッケージに関わるエラーが出てしまう可能性が考えられるためです。

**Comment by potato4d** [comment]
これ、解消したくなった場合本家を先にやらないといけない :cry:
https://github.com/vuejs/vuejs.org

**Comment by kubosho** [comment]
😇

**Comment by kazupon** [comment]
本家にissue投げるといいかもしれないですね

**Comment by potato4d** [comment]
@kubosho 
これ、一旦 https://github.com/vuejs/vuejs.org に投げてみてもらっても良いですか :pray:
通ればこちらも反映します（ちょっと日本語訳バージョンは専用の TextLint とか入ってて面倒なんですが、まぁ一旦そこはおいといて）
