### ISSUE TITLE
"Installation" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#126]
英語: [Installation](http://rc.vuejs.org/guide/installation.html)
翻訳対象: src/guide/installation.md

**Comment by satotakumi** [comment]
@kazupon 
やります！ ✋ 
1.0とほぼ変わっていないと思うのですが、翻訳されてる部分はそのまま持ってくるという形でも問題ないのでしょうか？

**Comment by kazupon** [comment]
@satotakumi
同じ内容なら、特に問題ありません。

翻訳、よろしくお願いします。
