### ISSUE TITLE
Add GitHub template

### ISSUE THREAD

**Issue by potato4d** [vuejs/jp.vuejs.org#1273]
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#github-issues-%E3%81%AB%E3%81%82%E3%82%8B%E6%9C%AC%E5%AE%B6%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AE%E5%B7%AE%E5%88%86%E6%9B%B4%E6%96%B0%E5%86%85%E5%AE%B9%E3%82%92%E7%BF%BB%E8%A8%B3%E3%81%97%E3%81%A6%E8%B2%A2%E7%8C%AE%E3%81%99%E3%82%8B にコントリビューションのヒントが書かれているし、ある程度 .github でテンプレートを書いてもよいのでは？という気がしてきました。

**Comment by kazupon** [comment]
それいいですね！ 👍
