### ISSUE TITLE
[TodoMVC Example] [enter] key event to determin transform of Japanese characters makes the item added to list

### ISSUE THREAD

**Issue by FumioNonaka** [vuejs/jp.vuejs.org#1338]
## 概要
日本語変換を確定する[enter]キーで項目が追加されてしまいます。

## 詳細
「[TodoMVC の例](https://jp.vuejs.org/v2/examples/todomvc.html)」で日本語入力時、[enter]キーで変換候補を選ぶと、ユーザーはまだ入力中のつもりなのに、その項目がリストに追加されてしまいます。

## 参考資料など
「[Vue.js: TodoMVCの例で日本語の項目が正しく入力できるようにする](https://qiita.com/FumioNonaka/private/2dfb272156e48cfcf824)」

キーイベントを`keypress`に改め、[enter]キーであることを確かめて追加するようにすれば、変換確定で処理はされません。

修正例「[TodoMVC revised](https://jsfiddle.net/FumioNonaka/38uvnawh/)」

なお、v2.3.4では、`keydown`イベントは日本語変換を確定する[enter]キーは拾いませんでした。標準JavaScriptの`keydown`イベントも同じです。現在の動作は仕様変更でしょうか。

**Comment by kazupon** [comment]
Issue レポートありがとうございます ✨ 

確認したところ、バージョン `2.5.14` で仕様変更したようです。
参考 issue はこちらです。
https://github.com/vuejs/vue/issues/9000

ただ、Vue.js 公式 example の TodoMVC、この仕様変更に対応していないのは、あまりよろしくないので、本家公式ドキュメントレポジトリ `vuejs/vuejs.org` レポジトリに issue 報告した方がよさそうです。
https://github.com/vuejs/vuejs.org/issues

もしくは OSS なので PR 送って頂けると、コアチーム側としては大変助かります。 🙇

**Comment by FumioNonaka** [comment]
`examples/todomvc/index.html`を修正しました。Pull requestするにはpermissionをいただく必要があるでしょうか。
> Git: remote: Permission to vuejs/vue.git denied to FumioNonaka.

**Comment by kazupon** [comment]
ありがとうございます！

Pull Request するには、 [vuejs/vue](https://github.com/vuejs/vue) レポジトリを自分のアカウントにフォークし、そのレポジトリ上で編集する必要があります。
別ブランチを作って修正をコミット後、自分の該当レポジトリにpushし、その後、GitHub上で `vuejs/vue` レポジトリに Pull Requestする形になります。

**Comment by FumioNonaka** [comment]
ありがとうございます。pull requestに加えました。

「[Changing keyup to keypress to properly deal transform of Japanese chars](https://github.com/vuejs/vue/pull/9172)」 #9172

**Comment by kazupon** [comment]
マージされたのcloseします。
ありがとうございました！
