### ISSUE TITLE
"Components" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#136]
英語: [Components](http://rc.vuejs.org/guide/components.html)
翻訳対象: src/guide/components.md

**Comment by kdnk** [comment]
担当したいです！

**Comment by kazupon** [comment]
@kdnk ありがとうございます！では、よろしくお願いします！

**Comment by kazupon** [comment]
/ping @kdnk 
翻訳作業の方、いかがでしょうか？
そろそろ宣言されてから1ヶ月近くになりますので、よろしくお願いします！ :bow:

**Comment by kdnk** [comment]
時間かかってしまいすみません！
今週中にPRします！

**Comment by kazupon** [comment]
よろしくお願いします！！
