### ISSUE TITLE
Markdownが正しくレンダーされていない?

### ISSUE THREAD

**Issue by ghost** [vuejs/jp.vuejs.org#1362]
## 概要
https://jp.vuejs.org/v2/guide/instance.htmlに _追跡_ とあるが、これが斜体として表示されず、\_追跡\_と表示されている

**Comment by oohira** [comment]
以前私も気になったのですが、Hexo側の不具合っぽいです。

* https://github.com/hexojs/hexo-renderer-marked/issues/70

**Comment by ghost** [comment]
ローカルでいろいろやってみたんですが、\_追跡\_ではなく\*追跡\*に変えると正しくレンダーされるみたいです。
