### ISSUE TITLE
"Transitions: Entering, Leaving, and Lists" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#137]
英語: [Transitions: Entering, Leaving, and Lists](http://rc.vuejs.org/guide/transitions.html)
翻訳対象: src/guide/transitions.md

**Comment by kitak** [comment]
翻訳したいです 🙋

**Comment by kazupon** [comment]
@kitak ありがとうございます！では、よろしくお願いします！
