### ISSUE TITLE
"Custom Directives" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#141]
英語: [Custom Directives](http://rc.vuejs.org/guide/custom-directive.html)
翻訳対象: src/guide/custom-directive.md

**Comment by massa142** [comment]
🙋🙋🙋

**Comment by kazupon** [comment]
@massa142 ありがとうございます！ではよろしくお願いします。

**Comment by kazupon** [comment]
@massa142 
翻訳作業の方、いかがでしょうか？
そろそろ宣言されてから1ヶ月近くになりますので、よろしくお願いします！ :bow:

**Comment by massa142** [comment]
@kazupon 進捗なくてすみません :bow:
今週PR出せるように翻訳進めます。

**Comment by kazupon** [comment]
@massa142 
よろしくお願いします！！
