### ISSUE TITLE
"Unit Testing" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#147]
英語: [Unit Testing](http://rc.vuejs.org/guide/unit-testing.html)
翻訳対象: src/guide/unit-testing.md

**Comment by mikakane** [comment]
こちら担当させて下さい。

**Comment by kazupon** [comment]
@mikakane 
ありがとうございます！
では、よろしくお願いします。 👍

**Comment by mikakane** [comment]
https://github.com/vuejs/jp.vuejs.org/pull/166
PR作成しました！
