### ISSUE TITLE
v2.6の翻訳方針

### ISSUE THREAD

**Issue by oohira** [vuejs/jp.vuejs.org#1472]
## 概要

v2.6 の更新を翻訳する際の進め方について相談したい

## 背景

vuejs-jp-bot が master ブランチ上でのドキュメント更新を Issue 化してくれていますが、Issue が作成されている順番と実際のコミット順が違うようです。

また、#1458 `3cd3e69 Merge pull request #1939 from vuejs/2.6` のマージコミットにv2.6のすべての修正が含まれており、その他の Issue は途中コミットなので無視してよいようにも見えます（若干自信なし）。

```sh
$ git log --graph --oneline vuejs/master
* e60d172 chore: update sponsor image
* 75d4c5a chore: update sponsor image
* 1726c7e fix: broken link
*   3cd3e69 Merge pull request #1939 from vuejs/2.6
|\
| * f39e3e0 2.6: add clarification about mixing abbreviated default slot w/ named slots
| * 845fff2 Revert "2.6: document shorthand for v-bind .prop modifier"
| * 77674dd mark scope as removed instead of replaced in api
| * 985c4b7 tweaks to v-slot docs
| * 8c762d9 syntax guide tweaks for v2.6
| * 2908c49 specify browser build is for using native es modules
| * 55ef7e2 small api tweaks/fixes
| * 0830fc3 fix scopedSlots typos and add more info
| * 07a9bd4 clarify behavior for Vue.observable
| * 3945e1d 2.6: improve v-slot api entry
| *   bff457f Merge branch 'master' into 2.6
| |\
| * | 825c21b 2.6: v-slot api entry
| * | 70c7b63 2.6: update slot guide
| * | 535a48d 2.6: make dynamic argument constraint more noticable
| * | 1f5b2c9 2.6: more examples for dynamic arguments
| * | 746f128 2.6: dynamic arguments
| * | cdf7ca3 2.6: add a note about functional context scopedSlots also exposing normal slots
| * | 1aa6780 case tweak
| * | eb9c932 2.6: apply suggestions from code review
| * | 2d7a918 2.6: document v-for iterable support
| * | 036bf19 2.6 document scopedSlots on functional context
| * | 3ca4eea 2.6: document errorHandler improvements
| * | 5295c84 2.6: document $scopedSlots changes
| * | f639b83 2.6: document shorthand for v-bind .prop modifier
| * | 177f0af 2.6: document Vue.observable
| * | 190279d 2.6: document ESM browser build
* | | 5e1911b chore: update sponsors <------------------------（ここまではだいたい翻訳済みのはず）
* | | 9ed4e09 Added Gregg + Adam & Mixins free lesson link (#1981)
* | | 7600664 chore: update sponsors (#1978)
* | | 60fe0c0 chore: update sponsors (#1973)
* | | 7d0ed2f Use Enter and submit in keyboardEvent example (#1970)
* | | 1b68103 Add clarification about `inheritAttrs` and class/style bindings (#1787) (#1969)
* | | 127443e Use highlight.js (#1968)
| |/
|/|
* | 1a73684 Remove myself from emeriti and add official repo back (#1967)
* | 642efaa Added community partner Filip Rakowski (#1960)
* | 0632870 remove deprecated repos from my team page profile (#1966)
* | 67766e4 Update Key Modifiers to suggest KeyboardEvent.key (#1850)
* | 42c313c Adding new Spanish translation credits. (#1940)
...
```

## 相談

翻訳とレビューをどのように進めるのがよさそうでしょうか？

* 案1. #1458 を一気に翻訳してPRを作成する
  * Good: revertやブラッシュアップなどの途中の無駄な修正を翻訳しなくてよい
  * Bad: 一度にレビューするのが大変。分担もしづらい
* 案2. #1458 をファイル毎などで分割して個別に翻訳してPRを作成する
  * Good: 案1 よりは小さな単位になるので翻訳・レビューがしやすい。ファイル単位で分担もできる
  * Bad: ファイルによっては修正が多いので、一度にやるのもさほど変わらないかも
* 案3. vuejs-jp-bot の Issue を古い方から翻訳してPRを作成していく
  * Good: 小さな差分になるので翻訳・レビューはしやすい
  * Bad: 無駄な翻訳・レビューが発生し、何より最終版相当になるのか不安

レビューの単位とは別に、lang-ja ブランチに反映するタイミングもありそうです。v2.6 の翻訳がすべて終わってから一気にマージした方がユーザーの混乱が少ないのか、一部分ずつでも v2.6 の情報が入っていった方が嬉しいのか。

いつもこうしているなどの方針があれば教えていただけるとありがたいです。よろしくお願いします。

**Comment by kazupon** [comment]
@oohira 
2.6の翻訳提案ありがとうございます！
ちょうど、こちらこれから対応しようかと思っていました。

方針としては、 `案1` の #1458 を一気に翻訳してPRを作成する方が、ユーザーに混乱を与えず、一気にプロダクション環境のドキュメントに反映されるのでこちらがよいです。
botがバグ？って #1458 の途中のコミットを issue として作ってしまっているようですが、こちらは今回の翻訳ではとりあえず無視していただいて大丈夫です。

一気に翻訳するとなるとレビューが大変になりますが、こちらは致し方がないですが、それでもレビューしやすい工夫をしたいところです。

案としては、

1. #1458 の各コミットの原文を日本語の方にそのまま取り込む
1. その後、翻訳する

とすることで、一旦 1. のコミットで原文が入る形になるので、 2. の翻訳のときには、原文を見ながらレビューすることができると自分が考えています。

@potato4d @re-fort 
お忙しいところすいませんが、何か妙案があればコメント下さい！ 🙏

**Comment by kazupon** [comment]
@oohira 
コメントなさそうなので、この方針でお願いします。 🙏

**Comment by oohira** [comment]
@kazupon 確認ありがとうございます！1, 2 が両方終わってから `lang-ja` ブランチにマージするイメージだと思いますので、v2.6用の作業ブランチを作っていただくことは可能でしょうか？

1. [x] v2.6翻訳ブランチを作成
1. [x] #1458を取り込んで（原則は英語のまま、conflict箇所は軽微なら翻訳）、v2.6翻訳ブランチにPR
    * #1458のdiffと比べながらレビュー
1. [x] 未翻訳箇所を適当な単位で翻訳して、v2.6翻訳ブランチにPR
    * PRのdiffで原文と翻訳後の日本語を比べながらレビュー
    * [x] /api/index.md
    * [x] /guide/components-slots.md
    * [x] /guide/installation.md
    * [x] /guide/render-function.md
    * [x] /guide/syntax.md
1. [x] すべて終わったらv2.6翻訳ブランチからlang-jaブランチにマージ
1. [x] 翻訳済みの既存 Issue をクローズ

**Comment by kazupon** [comment]
@oohira 
`v2.6` ブランチ作りました。
https://github.com/vuejs/jp.vuejs.org/tree/v2.6

よろしくお願いいたします。 🙏

**Comment by potato4d** [comment]
今ざっくり目を通しました。方針よさそうです！
今既に進められているのが見えるので、ちょっとレビューだけのお手伝いになってしまいますが、見ていきたいと思います！

**Comment by kazupon** [comment]
@oohira 
#1513 でマージしました。

もし、可能なら、 `5\. 翻訳済みの既存 Issue をクローズ` を対応していただけると助かります。 🙇 
難しいようでしたら、こちらで対応します。

**Comment by kazupon** [comment]
関連issue、一通りcloseしたので、このissueも閉じます

**Comment by oohira** [comment]
@kazupon すでにcloseしていただいているものもありますが、私が把握できているものは一通りコメントを追記しましたので、確認お願いします。もろもろフォローありがとうございました！ 😄
