### ISSUE TITLE
"Migration from Vue 1.x" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#149]
英語: [Migration from 1.x](http://rc.vuejs.org/guide/migration.html)
翻訳対象: src/guide/migration.md

**Comment by potato4d** [comment]
こちら翻訳やってみたいと思います。
よろしいでしょうか？

**Comment by kazupon** [comment]
@potato4d ありがとうございます！では、よろしくお願いしいます！

**Comment by potato4d** [comment]
@kazupon 
では進めてまいりますね！
ちなみに、1つ質問なのですが、「セクションごと」というとどういう区切りになりますでしょうか？
今回の場合、`Migration from Vue 1.x`を一つの大きなセクションとして定義して、全体を翻訳していくかたちで間違いありませんでしょうか？

**Comment by kazupon** [comment]
@potato4d
少し分かりづらかったですね。
すいません。
セクションですが、src/guide 配下にあるmarkdownファイル単位のことですね。
ブラウザでの表示は目次的に1つのセクションつまりページになるので、そこから来ています。
なので、今回こちらのissueはまさに、'Migration from Vue 1.x' がセクションに相当します。
他と比べるとボリュームが大きくて大変かもしれませんが、訳し終えたときには、1.x からの差分について理解できていると思います。💪

**Comment by potato4d** [comment]
@kazupon 
詳しくありがとうございます！
ちょうど1.xを使っていて、2.0に移行していきたいところですので、翻訳しながら学んでいきたいと思います。

**Comment by kazupon** [comment]
/ping @potato4d 
翻訳作業の方、いかがでしょうか？
そろそろ宣言されてから1ヶ月近くになりますので、よろしくお願いします！ :bow:

**Comment by potato4d** [comment]
@kazupon
中々手間取ってしまっていて申し訳ございません！
今大方翻訳が済んだところでして、ちょうど明日のお昼頃にはPull Requestを投げられるかなというところとなります。

幾つか、翻訳でわからないところがありますので、ご質問してもよろしいでしょうか？

**Comment by kazupon** [comment]
@potato4d 
👍 
PR駆動でとりあえず投げて、
レビューで質問していただいて大丈夫です :)
