### ISSUE TITLE
URLをja.vuejs.orgに移行してほしい

### ISSUE THREAD

**Issue by myakura** [vuejs/jp.vuejs.org#1534]
## 概要

`jp`は国コードを指しており、翻訳においては言語コードである`ja`を使うのが一般的であるため。

## 詳細

翻訳やにおいては、国コードではなく言語コードをまず使います。

例：
* https://developer.mozilla.org/ja/
* https://ja.wikipedia.org/
* https://github.com/reactjs/ja.reactjs.org

国によってビジネスの範囲やスペルなどが異なる場合は国コードを付加しますが、日本語の場合はあまり考えなくても良いでしょう。

現行のjp.vuejs.orgが提供するコンテンツが「日本人」や「日本国」を対象とする目的であれば現行のままでいいかもしれませんが、そういった性質は見られません。

であれば「日本語」での情報であることを示せる言語コードの`ja`を使う方が、「日本語を使うすべての人」を対象として見せられるので、幅広いバックグラウンドの方を受け入れるコミュニティとしても適切ではないでしょうか。

## 参考資料など

- 対象ファイル
  - jp.vuejs.org を指しているファイルすべて

**Comment by potato4d** [comment]
提案ありがとうございます :pray:

### Vue.js / JavaScript における日本語ドキュメントの URL 設計について

#### JavaScript フレームワーク

- https://ja.reactjs.org/
- https://angular.jp/

#### Vue.js エコシステム

- https://router.vuejs.org/ja/
- https://vuex.vuejs.org/ja/
- https://ja.nuxtjs.org/

という具合になっており、確かに Vue.js 日本語ドキュメントより後発で作られたドキュメントは国コードではなく言語設定を遵守しており、こちらのほうが妥当性が高いと認識しています。

### 考慮点

しかし一方で、 https://jp.vuejs.org は既に非常に多くの Web サイトや書籍などから引用されているほか、広く一般に知られてしまっているため、個人的にはそのままでも問題ないと考えています。

作業コストとしてはリダイレクト程度で基本hなそこまで重くないと認識しているものの、もしかしたら権限の都合上 Evan 依頼タスクなどがでてくると大きな作業となりそうな気もしています。
いずれにせよ十分に検討し、影響範囲を一通り洗った上で、行うかどうかの結論をだすべきだと考えています。

- - -

@kazupon @re-fort @inouetakuya @aytdm @potato4d
ひとまず Vue.js 周りのドキュメント管理しているメンバーの意見を募りたいです。

**Comment by potato4d** [comment]
思いつく限りのタスクとしては

- ja.vuejs.org の DNS 設定の反映
- ja.vuejs.org の Netlify 作成
- ja.vuejs.org への jp.vuejs.org のデプロイ
  - 同時に jp.vuejs.org の canonical を ja.vuejs.org に向ける
- jp.vuejs.org のリダイレクト設定
- vuejs/jp.vuejs.org の Repo を ja.vuejs.org へとリネーム
- Vue.js / Vuex / Vue Router 辺りのドキュメントについてリンクを張替え

あたりでしょうか

**Comment by kazupon** [comment]
そうですね。
移行コストを考えると、現状のままでよい気がするんですが、こちら最初に `jp` 決めてしまった自分としては、 前から `ja` に移行したいと、心の底で思っていました。

Vue 3.0 のリリースが今年あるので、そのタイミングで`ja.vuejs.org` に移行するのがいいかもしれません。

リダイレクトは、Netlify のリダイレクト機能使えば、簡単に済んでしまうかもしれませんが、現状ドキュメントの参照が高いので、影響範囲は洗い出した方がいいですね。
https://www.netlify.com/docs/redirects/#handling-hostnames-and-protocols-differently

**Comment by kazupon** [comment]
>もしかしたら権限の都合上 Evan 依頼タスクなどがでてくると大きな作業となりそうな気もしています。

こちらは、私の方で Evan にお願いすれば、ドメイン対応してくれるはずです。

**Comment by potato4d** [comment]
Vue 3.0 リリースのタイミングに合わせるのは確かに自然そうですね。よさそう。

**Comment by inouetakuya** [comment]
> Vue 3.0 のリリースが今年あるので、そのタイミングで `ja.vuejs.org` に移行するのがいいかもしれません。

賛成です！！:raised_hands:

**Comment by kazupon** [comment]
新しいVue.js日本語公式ドキュメントで公開しましたので、close します。
https://ja.vuejs.org

**Comment by myakura** [comment]
@kazupon さん、コミュニティのみなさん、ドキュメントの公開おめでとうございます。提案も受け入れていただき、本当にありがとうございます。
