### ISSUE TITLE
APIドキュメントページのリンク誤り？

### ISSUE THREAD

**Issue by amedora** [vuejs/jp.vuejs.org#1570]
## 概要

APIドキュメントのページに張られているリンクで誤りと思われるものがありました。

## 詳細

問題のページは以下です。
- https://jp.vuejs.org/v2/api/index.html#v-once

『参照』に挙げられている『コンポーネント - v-once による安価な静的コンポーネント』を
クリックすると、[『動的なコンポーネント』](https://jp.vuejs.org/v2/guide/components.html#%E5%8B%95%E7%9A%84%E3%81%AA%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88)のページに遷移します。

本来意図している遷移先のページは[『v-once を使用するチープスタティックコンポーネント』](https://jp.vuejs.org/v2/guide/components-edge-cases.html#v-once-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%83%81%E3%83%BC%E3%83%97%E3%82%B9%E3%82%BF%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88)と思われます（英語版のページではそうなっています）。

## 参考資料など

Windows7のChrome 73.0.3683.75 で確認しました。

**Comment by oohira** [comment]
@kazupon 原文ではリダイレクトを使ってセクションの移動を吸収しているようですが、翻訳文ではこの仕組みを使っていないためうまく遷移できなくなっているようです。この手のリンク切れは他にも結構ありそうですが、現状の方針としては「リダイレクトを使わずリンクを直接目的のページに飛ぶよう直す」が正しいでしょうか

* themes/vue/source/js/common.js

```
88:      'Cheap-Static-Components-with-v-once':
89:        '/v2/guide/components-edge-cases.html#Cheap-Static-Components-with-v-once'
```

**Comment by kazupon** [comment]
@oohira 
>現状の方針としては「リダイレクトを使わずリンクを直接目的のページに飛ぶよう直す」が正しいでしょうか

これまで、日本語公式ドキュメントの方はリダイレクトを使わずに、対応する日本語ドキュメントのURLに直接リンクする形でやってきました。
対応方法については、原文がリダイレクトで対応している方法と、これまでやってきた直接リンクする方法とがあります。
リダイレクトの方が一元管理できるのでメンテナンス面の観点で、そちらの方がいいのと、なるべく原文と同じ方法しておいた方が、原文と日本語の翻訳形式のやり方の差分をなくした方が、今後のためになるので、原文と同じリダイレクトで対応する方法がよいです。

**Comment by oohira** [comment]
@kazupon ちょっと悩ましいかもしれません。次の2通りの方法が考えられますが、どちらもイマイチな気がします。

* 元文書からは日本語ハッシュでリンクする
    * 翻訳済みの文書が本家側である日ページ分割されてリダイレクト設定されたと考えると、こちらが自然
    * ただし、実際にはこのままでは動作しない（キーの部分をURLエンコードした文字列にする必要があるので可読性を犠牲にして `v-once-%E3%82%...` のように宣言するか、本家とdiffが出る覚悟で `map[encodeURIComponent('v-once-を使用...')] = '...'` のようにJSを変えてしまうか）

```js
  'v-once-を使用した安価な静的コンポーネント':
    '/v2/guide/components-edge-cases.html#v-once-を使用するチープスタティックコンポーネント'
```

* 元文書からは英語ハッシュでリンクする
    * 元文書は翻訳済みなのでリダイレクト設定される前はすでに日本語ハッシュのリンクになっているはずで、いちいち英語ハッシュに戻さなければならなくなってしまう

```js
  'Cheap-Static-Components-with-v-once':
    '/v2/guide/components-edge-cases.html#v-once-を使用するチープスタティックコンポーネント'
```

**Comment by kazupon** [comment]
@oohira 
うーん、悩ましいですね。。。
これまで、直接リンクしていたときも、リンクのハッシュ部分は日本語でURLエンコードしていたので、最初の案の方でいきましょうか。

/cc @potato4d @re-fort 
何か妙案があればコメントお願いします。:pray:

**Comment by oohira** [comment]
@amedora ご報告ありがとうございました 👍
