### ISSUE TITLE
VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [vuejs/jp.vuejs.org#1658]
Hello @kazupon, @re-fort, @potato4d, and @oohira! 

My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Japanese translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

**Comment by kazupon** [comment]
Hello @bencodezen !
Thank you for asking!  😄 

We're interested in that migration.
I have some question.

- Is document migration assumed to be v2 based? Or assumed to be v3 release?
- Would the content of the document change significantly? If In that case, we need to start as a translation project.

And, Could you share the background explanation of why it happened, please?
I'm a core team member of Vue.js, so I know a little bit about the background, but  Japan maintenance member don't know about it.

and one more thing, I have a suggestion.
Like React.js or Nuxt, how about starting up the community organization and organizing the Vue.js official documents in that organization?

https://github.com/reactjs
https://github.com/nuxt-community

As an early core member of Vue.js, I have seen the Vue.js community grow along with the growth of Vue.js so far.
In such an environment, we know that our core team members are contributing to the growth of Vue.js.

By providing a place where the Vue.js community can lead activities, such as documentation and translation, I believe in a community organization that has started up can give incentives and motivation of contribution to the Vue.js community. as that result, so our Vue.js core team and Vue.js community will be given good results. 😸

**Comment by bencodezen** [comment]
Hello @kazupon!

The document migration will be v2 based in order to make the transition easier for all of the team.

The plan is to keep the content identical by issuing a content freeze during the transition. We plan to do it quickly so updates can resume as soon as possible.

As far as the reason behind this migration...

1. In case you didn't know, VuePress is a documentation tool that Evan built and is being adopted by a lot of libraries; but the core docs still don't use it.
2. In order to better facilitate use of VuePress and use our own product, it seemed that this was a good time to migrate the infrastructure in order to better unify the ecosystem.

In terms of your suggestion for having a central community organization, I think that's a great idea. I'll make sure to bring it up to the team!

**Comment by bencodezen** [comment]
If anyone has any additional feedback, please don't hesitate to re-open the issue and/or tag me in a new one!

**Comment by oohira** [comment]
@bencodezen Sorry for late reply. It is not about the migration, but I feel a little pain for the hexo's feature to generate anchor link automatically. It is useful when we write documents, but troubles us when we translate them because we also have to change the anchor of the link.

In original document

```
... [prop](components.html#Props) ...
```

In Japanese document (`#プロパティ` depends on the translated section title in components.html)

```
... [プロパティ](../guide/components.html#プロパティ) ...
```

It tends to produce a broken link when original document's section title is changed. I don't know VuePress well, but it is good news if it has a feature to define the anchor link explicitly.

**Comment by bencodezen** [comment]
Hi @oohira! Thank you for raising your concerns. If I understand your concern correctly, VuePress totally allows you to change the anchor link explicitly in the way you desire, so you should be totally covered in this regard. 

Let me know if you have any other questions or concerns!
