### ISSUE TITLE
"Migration from Vue Router 0.7.x" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#172]
英語: http://rc.vuejs.org/guide/migration-vue-router.html
翻訳対象: src/guide/migration-vue-router.md

**Comment by mikakane** [comment]
こちら担当させて下さい！

**Comment by kazupon** [comment]
@mikakane ありがとうございます！では、よろしくお願いいたします！

**Comment by mikakane** [comment]
@kazupon ありがとうございます。
翻訳前に幾つか確認させて下さい！

## 1. サイト内で頻繁に使用されるTipsの翻訳

こちら該当箇所多いので先に表記確認させて下さい。下記のような翻訳で良いでしょうか？

英：

```
{% raw %}
<div class="upgrade-path">
  <h4>Upgrade Path</h4>
  <p>Run the <a href="https://github.com/vuejs/vue-migration-helper">migration helper</a> on your codebase to find examples of <code>router.map</code> being called.</p>
</div>
{% endraw %}
```

日：

```
{% raw %}
<div class="upgrade-path">
  <h4>移行ガイド</h4>
  <p>コードに対し <a href="https://github.com/vuejs/vue-migration-helper">移行ヘルパー</a> を実行し <code>router.map</code> がコールされる箇所を検出して下さい。</p>
</div>
{% endraw %}
```

## 2. Vue ルータドキュメントのリンク先について

英語のドキュメントへのリンクが貼られていますが、こちら日本語のものに差し替えますか？
(Vue Router 2.0のドキュメント翻訳状況ってどのようになってましたっけ…？)

## 3. Vue Router の翻訳

Vue Router は ルータでしょうか？ルーターでしょうか？

お手数ですが、アドバイスもらえると助かります！

**Comment by kazupon** [comment]
> `1. サイト内で頻繁に使用されるTipsの翻訳`

おおむねよいです。

> `2. Vue ルータドキュメントのリンク先について`

リンク先は、日本語でお願いします。

> `3. Vue Router の翻訳`

ルーターで翻訳しておいてください！

以上、よろしくお願いします！
