### ISSUE TITLE
[Guide] Security guide の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs/jp.vuejs.org#1896]
## 概要

https://github.com/vuejs/jp.vuejs.org/pull/1895 にて新規ドキュメントが追加されたので翻訳を行う。

## 詳細

対象: https://github.com/vuejs/jp.vuejs.org/commit/7ec9bffe1c0742625ccb2601aefba2a5f94f62c5#diff-c71aaae2ab2d91d9ffc8cc8f6df314e6

**Comment by unotovive** [comment]
やりたいです✋

**Comment by potato4d** [comment]
@unotovive お願いします！
