### ISSUE TITLE
提案：「Single File Components」の日本語訳を「シングルファイルコンポーネント」に変更

### ISSUE THREAD

**Issue by munierujp** [vuejs/jp.vuejs.org#2007]
## 概要
Vue.jsの公式ドキュメントでは、「Single File Components」が「単一ファイルコンポーネント」と訳されています。

[単一ファイルコンポーネント — Vue.js](https://jp.vuejs.org/v2/guide/single-file-components.html)

それを、「シングルファイルコンポーネント」に変更するのはどうでしょうかという提案です。

## 理由
「シングルページアプリケーション」など、「Single」を日本語に訳す場合に「シングル」というカタカナ英語を用いることは一般的であり、「Single File Components」というVue.js界におけるある種の固有名詞にあたる用語の訳としてもふさわしいため。

**Comment by potato4d** [comment]
### FYI

この要望は以前から確かにある要望だったりします。

前に一度話したトピックなのですが、前回はこんな感じの議論で据え置きになりました

https://github.com/vuejs/vue-test-utils/issues/950

**Comment by munierujp** [comment]
@potato4d 他のリポジトリで過去に議論済みだったのですね。ありがとうございます :bow:
一連の議論を読みましたが、私はどちらかと言えば38elementsさんの意見に賛成ではあるものの、その後のやりとりにおいてkazuponさん、ktsnさん、potato4dさんらがおっしゃっていることにも合点がいきました。
ということで、このイシューは閉じさせていただきます。
