### ISSUE TITLE
what is '糖衣構文' ?

### ISSUE THREAD

**Issue by Hiroshiba** [vuejs/jp.vuejs.org#207]
https://github.com/vuejs/jp.vuejs.org/blame/9db9ca643ff72eb1ff24f43afa7672c69fa1cbb5/src/v2/guide/components.md#L543

'同一' or '等意' or ...
Thanks.

**Comment by ktsn** [comment]
糖衣構文 is a translation of *syntactic sugar* that means an alternative syntax of some existing syntax and it reduces our keyboard typing and let the code base be simpler.
https://ja.wikipedia.org/wiki/%E7%B3%96%E8%A1%A3%E6%A7%8B%E6%96%87

**Comment by kazupon** [comment]
Yes, @ktsn just said it!
Thanks!
