### ISSUE TITLE
Vue 3 Docs are ready for translation!

### ISSUE THREAD

**Issue by bencodezen** [vuejs/jp.vuejs.org#2217]
Hello! Just wanted to let you know that v3 docs are ready to start translating.

https://github.com/vuejs/docs-next

If you have any questions, please feel free to file an issue so we can help however we can!

**Comment by potato4d** [comment]
We will proceed with the following repository!
https://github.com/vuejs-jp/ja.vuejs.org

**Comment by kazupon** [comment]
@potato4d
Could you tell us about your idea of how to translate?
Or, if you have resources (information) on how to translate, we'd love to have them available to us.

If you can present it to us, @bencodezen  and docs team would helpful! :pray:

**Comment by potato4d** [comment]
ひとまず詳細についてはちょっと更に整えて書きますが、現状この方針で整備を進める予定ですー。
英語でのまとまったフロー詳細については少しお待ちください :man-bowing: 

- v3 ドキュメントは暫定的に vuejs-jp/ja.vuejs.org で管理する
  - しばらくは v2 ドキュメントのメンテナンス・v3ドキュメントの翻訳が並行で進むため
  - v3 ドキュメントの翻訳が完了した段階で、 vuejs/jp.vuejs.org はアーカイブする
    - この際、 vuejs/ja.vuejs.org へと移管するかは未定である
      - @kazupon これについて意見はありますか？
      - jp など一部だけが例外的に vuejs organization にある状態をきれいにするなら、 vuejs-jp で今後は運営するのもありだと思っています。
- 初期の翻訳については、 GitHub Issue と Project を利用する
  - 声を上げた人をアサインし、適宜貢献してもらう
  - そのセクションは、ルーティングごととする
- 翻訳の追従フローについては、現状の che-tsumi の方式をとる
  - つまりは upstream: vuejs/docs-next である
    - upstream の変更の追従を受けつつ、翻訳を進める
  - 可能であれば、 docs-next から next が外れたタイミングで、Actions などを用意して本家から通知が飛んでくるような仕組みにはしたい
    - が、@potato4d はしばらくそこにはリソースを割けない気がする……

**Comment by potato4d** [comment]
最終的な移管が終わるまでのホスティング先については、今後本家(en)が v3 と v2 のドキュメントをどうやって管理していくかによって変わる気がしていて、ちょっとそっちの事情を自分がキャッチアップする必要がありそうです

**Comment by kazupon** [comment]
おやすみのところ、起こしてしまってすいません。 🙇 

方針検討ありがとうございます！
よさそうです！

vuejs/jp.vuejs.org の移管ですが、今回を気に、vuejs-jp/ja.vuejs.org に移管したいと思っています。
vuejs の org にホストして運営するのは、アクセスできない(権限がない、ジョインできない) くて厳しいので、移管したいと思います。

本家からの通知ですが、これは GitHub Actions でやりたいですね。
この辺も、今回の翻訳の一環で、メンバーの誰かに、仕組み導入してしまってもいいと思います。
v3 と v2 のドキュメント管理方式、本家今後変わるので、GitHub Actions で差分通知する際にも考慮する必要ありそうです。
現時点では、本家の方は、バージョンごとサブドメイン分けてホストする方向で動いています。
数日後に、これは決まる予定です！

**Comment by potato4d** [comment]
@kazupon 

> vuejs/jp.vuejs.org の移管ですが、今回を気に、vuejs-jp/ja.vuejs.org に移管したいと思っています。
> vuejs の org にホストして運営するのは、アクセスできない(権限がない、ジョインできない) くて厳しいので、移管したいと思います。

ですよねー。私もその方針に同意です。
ドキュメント管理方式、本家の方針が決まった段階で Actions 化していきたいですね。

もしよかったら翻訳もある程度進んでそうな 9/3, 9/4 辺りで Vue.js JP の UG でディスカッションしながら本家に仕組みを導入するコントリビュートの機会なんかを設けるのも良いかなと思いました。

> 現時点では、本家の方は、バージョンごとサブドメイン分けてホストする方向で動いています。
了解です。その場合 ja.v3.vuejs.org にするのかなどの話が出てくると思うので、また共有お願いいたします。

---

それはそれとして、ひとまず v3 翻訳のフローは全部制定してみました。これまでの翻訳含めて基本的な特徴は以下です。

- 全体進行は Epic Issue を持ちつつも、 GitHub Projects で進行する
- 翻訳ルールはひとまず v2 のガイドラインに従う
  - https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md
- 翻訳はページごとに行う(担当者は一人)
- 特定のページに対するコミュニケーションで全体進行が混沌とすることを避けるため、個別の Issue を用意する
- 翻訳期間は1~2週間とし、その間に進捗がない場合は他の人が巻き取っても良いこととする

この辺全部まとめたのが以下の Issue です！
https://github.com/vuejs-jp/ja.vuejs.org/issues/1

**Comment by oohira** [comment]
Vue 3 docs Japanese translation is now available, so I will close this issue.

* Vue 3 Japanese docs
    * https://v3.ja.vuejs.org/
* Japanese translation project repository
    * https://github.com/vuejs-jp/ja.vuejs.org

**Comment by kazupon** [comment]
Thanks issue closing!
