### ISSUE TITLE
Vue 3ドキュメントへのリンクを差し替える

### ISSUE THREAD

**Issue by oohira** [vuejs/jp.vuejs.org#2234]
## 概要

Vue 2 ドキュメントからリンクする Vue 3 のドキュメントを日本語サイトのURLに切り替える

## 詳細

#2232 で Vue 3 を案内するバナーを表示するようになったが、[日本語翻訳プロジェクト](https://github.com/vuejs-jp/ja.vuejs.org) が進行中のため、リンク先はまだ英語ドキュメントになっている。日本語ドキュメントが公開されたら差し替える

## 参考資料など

* [x] d6a3eb009c4173613820f774f2e0b9a3125e0551 の 2箇所

**Comment by potato4d** [comment]
ちょっと日本語翻訳側はSW以降私が動けてなかったんですが、今晩or明日朝から動けそうなので溜まってる諸々は後ほど目を通して個別Issueで終わらせます🙇‍♂️

**Comment by oohira** [comment]
#2267 で修正済みなのでクローズします
