### ISSUE TITLE
"Style Guide" の翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#368]
## 背景

Vue.js のスタイルガイドが公式の下記ドキュメントとして公開されました。それに伴い、翻訳したい方を募集します。
https://vuejs.org/v2/style-guide/

## 翻訳該当ファイル

本レポジトリの下記ファイル

- src/v2/style-guide/index.md

## 貢献した際の特典

Vue.js 日本語公式サイトの[貢献ページ](https://jp.vuejs.org/contribution/)に、あなたの GitHub アカウントがクレジットとして掲載されます。

## 貢献方法
1. 翻訳したい方は、本 issue で、「翻訳やります！」的なコメントで宣言します :raising_hand:
2. メンテナである @kazupon に同 issue でコメントで承認されたら、正式に自分が選んだ issue の翻訳担当者としてアサインされたことになります
3. [このリポジトリ](https://github.com/vuejs/jp.vuejs.org)をフォークします!
4. 必要なら翻訳作業の環境をセットアップします: node.js のインストール、`npm install` など
5. `lang-ja` ブランチからトピックブランチを作成します: 例 `git branch style-guide lang`
6. [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md)に従って翻訳作業をします :pencil: 
7. 翻訳作業での変更をコミットします: 例 `git add src/v2/style-guide/index.md && git commit -am 'Fix some files'`
8. フォークした自分のレポジトリに Push します: 例 `git push origin style-guide`
9. 問題がなければ、プルリクエストを `vuejs/jp.vuejs.org` の `lang-ja` ブランチに送ります
10. レビュー :eyes: で指摘事項があったら修正し、再度 Push します :pencil:
11. レビュー :eyes: で OK ならば、マージされて担当した翻訳は晴れて終了になります! :tada:

## 翻訳における注意事項
- 翻訳の締切は OSS なので特に設けませんが、作業開始してレビュー完了まで含めて**だいだい 1 ヶ月以内ぐらいを目処**に進めて頂けると助かります :bow:
- Style Guide ですがまだ beta なので変更される可能性がありますが、翻訳開始時の内容で大丈夫です。差分はこちらで対応します。
- Style Guide かなり量が多いので、WIP(Work In Progress:作業中)な状態でプルリクエスト送り、区切りがよいセクション単位(段落)等で、適宜コミットしてその都度 Push して頂けると、レビュー :eyes: もしやすく、翻訳される方も気分的に楽になると思いますので、して頂ける助かります :pray:
- 翻訳作業を開始する際は、翻訳開始する際に、なるべく `lang-ja` ブランチの最新をものを使用してください。`lang-ja` は随時本家の最新内容を取り入れており、翻訳漏れが少なくなります
- 翻訳作業中に翻訳について不明点がある場合は、自分が翻訳宣言した issue にコメントお願いします :speech_balloon:

**Comment by zakuro9715** [comment]
🤚 翻訳やってみたいです！

**Comment by hisako135** [comment]
翻訳やります！ 🤚

**Comment by shika358** [comment]
作業開始が少し遅くなると思いますが､翻訳やります:hand:

**Comment by kazupon** [comment]
みなさん、ありがとうございます！
Style Guide 、大きく4つ(Priority A から D) あるので、もう一方表明された時点で締め切りたいと思います！
こちらGitHub Projects でチケット化してやってきたいと思います。

**Comment by wonderful-panda** [comment]
やります

**Comment by kazupon** [comment]
みなさん、翻訳表明していただきありがとうございます！ 🙏 
定員になったので、募集は締め切らせていただきます。

**Comment by kazupon** [comment]
早速ですが、GitHub Projects / Issues でチケットを切りました！
https://github.com/vuejs/jp.vuejs.org/projects/2

翻訳されたいチケット(Issue) を選んで、そのチケットで「これやります！」的なコメントしてください。
コメントされた時点で、翻訳の担当になります。

よろしくお願いいたします！ 🙏

**Comment by zakuro9715** [comment]
[Rule Categories](https://github.com/vuejs/jp.vuejs.org/blob/d11521761fd422228f72f2436a1864fe851912b0/src/v2/style-guide/index.md#rule-categories) の内容は現時点では各 issue の翻訳対象には含まれていませんが、それぞれのセクションに関連しているように思います。
なので、各 issue の翻訳対象含めてしまっても良いと思うのですが、どうでしょうか。

**Comment by kazupon** [comment]
@zakuro9715 
提案ありがとうございます！

/cc @hisako135 @shika358 @wonderful-panda 
こちらついては、私の方で翻訳しようかと思っていましたが、
もし可能でしたら、対応していただけると、大変助かります！ 🙏  😭

**Comment by potato4d** [comment]
@kazupon 
スタイルガイドの冒頭の文、こちらで翻訳してしまってよろしいでしょうか？

**Comment by kazupon** [comment]
@potato4d 
よろしくお願いします！ 🙏

**Comment by kazupon** [comment]
みなさん、翻訳ありがとうございました！
全て完了したのでクローズします！
