### ISSUE TITLE
"Priority A Rules: Essential" セクションの翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#372]
## 英語
https://jp.vuejs.org/v2/style-guide/#Priority-A-Rules-Essential-Error-Prevention

## 翻訳対象
`Priority A Rules: Essential` セクションの部分
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/style-guide/index.md#priority-a-rules-essential-error-prevention

## 関連 Issue (追記: 2017-10-02 23:31)
https://github.com/vuejs/jp.vuejs.org/issues/368

**Comment by chi-bd** [comment]
:raising_hand: やります

**Comment by hisako135** [comment]
これやります 🤚

**Comment by kazupon** [comment]
@hisako135 ではよろしくお願いします！ 🙏
