### ISSUE TITLE
"Priority B Rules: Strongly Recommended" セクションの翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#373]
## 英語
https://jp.vuejs.org/v2/style-guide/#Priority-B-Rules-Strongly-Recommended-Improving-Readability

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/style-guide/index.md#priority-b-rules-strongly-recommended-improving-readability

## 関連 Issue (追記: 2017-10-02 23:31)
https://github.com/vuejs/jp.vuejs.org/issues/368

**Comment by wonderful-panda** [comment]
やります。

**Comment by kazupon** [comment]
@wonderful-panda ではよろしくお願いします！ 🙏
