### ISSUE TITLE
"Priority C Rules: Recommended" セクションの翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs/jp.vuejs.org#374]
## 英語
https://vuejs.org/v2/style-guide/#Priority-C-Rules-Recommended-Minimizing-Arbitrary-Choices-and-Cognitive-Overhead

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/style-guide/index.md#priority-c-rules-recommended-minimizing-arbitrary-choices-and-cognitive-overhead

## 関連 Issue (追記: 2017-10-02 23:31)
https://github.com/vuejs/jp.vuejs.org/issues/368

**Comment by potato4d** [comment]
@kazupon 
これやりたいですー

**Comment by kazupon** [comment]
@potato4d 
すいません。Issue の説明不足でした。。。
実は、こちらのIssueで、すでに翻訳されたい方募集で締め切ってしまっていました。。。
https://github.com/vuejs/jp.vuejs.org/issues/368

申し訳ないです。 🙇

**Comment by shika358** [comment]
これやりますー💪

**Comment by kazupon** [comment]
@shika358 ではよろしくお願いします！ 🙏
