### ISSUE TITLE
Continuous deployment using netlify

### ISSUE THREAD

**Issue by yyx990803** [vuejs/jp.vuejs.org#634]
First all, 頑張ってくれてありがとう! 🙇

I have moved the deployment of vuejs.org to [Netlify](https://www.netlify.com/), which has automated continuous deployment whenever the github repo is updated. It removes the need of manual deployments, and from my testing also has better performance than GitHub pages (their CDN routes traffic from Asia to AWS Japan!)

If you guys are ok with this I can set it up easily, the only thing needed is having [this update](https://github.com/vuejs/vuejs.org/commit/42c9a22d7f4b813e8580249bdb98e1451d74c58a) cherry picked here.

**Comment by re-fort** [comment]
Thanks for your great effort too :bow:

Although we already achieve continuous deployment with Circle CI, hosting on Netlify has a  [good points](https://www.netlify.com/github-pages-vs-netlify/) compared to GitHub pages.
So I think it's good in terms of hosting.

How about @kazupon?

**Comment by kazupon** [comment]
@yyx990803 
Thank you for your proposal!
Good idea!
I think Netlify give better page load performance to Vue.js users.

Our translation work so far, In about deployment with Circle CI, we had been automated that deploy to GitHub pages, and had been checked the translation orthographical variants with `textlint`.

Recently, @re-fort improved to check the translation lint with `precommit`.
No longer we need to deploy with CircleCI.

We hope to move to Netlify.  :)

**Comment by re-fort** [comment]
@kazupon
Thanks!
Linting text when submitting a PR would still worth enabling on Circle CI, I think :)

**Comment by kazupon** [comment]
@re-fort 
Okay!
Let's remove the deployment from circleCI, and move to Netlify.
