### ISSUE TITLE
Cookbook

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/jp.vuejs.org#726]
まだbeta版ですが、https://vuejs.org/v2/cookbook/index.html も翻訳する予定はありますか？英語版に貢献していて、日本語に翻訳したい友達がいて、いちおう日本語にする予定があるか確認したかったです。

**Comment by kazupon** [comment]
@lmiller1990 はい！リリースされたら、もちろんやります！ 👍 
ぜひ、そのときにはよろしくお願いします！ 🙏

**Comment by kazupon** [comment]
@lmiller1990 
つい先日Cookbookのbetaが本家の方で公開されました。それに伴い、cookbook翻訳プロジェクトを開始したい思います。
issueはこちらです。
https://github.com/vuejs/jp.vuejs.org/issues/814

ぜひ、興味があったらご協力お願いします！ 🙏

**Comment by lmiller1990** [comment]
@kazupon Ok! Thanks!

Edit:　もう全部担当者がいるので、とりあえずレビューします！もし誰かができなくなったら僕がします。

**Comment by kazupon** [comment]
@lmiller1990 
すいません。 🙇 
レビューはよろしくお願いします！ 🙏 
一旦、このissue閉じますね。
