### ISSUE TITLE
[Cookbook]: 翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#814]
## 背景

Vue.js のCookbook(クックブック・レシピ集)が公式のドキュメントとして公開されました。
それに伴い、翻訳したい方を募集します。
https://vuejs.org/v2/cookbook/

## 翻訳対象
- [Introduction](https://vuejs.org/v2/cookbook/index.html)
- [Adding Instance Properties](https://vuejs.org/v2/cookbook/adding-instance-properties.html)
- [Form Validation](https://vuejs.org/v2/cookbook/form-validation.html)
- [Editable SVG Icon Systems](https://vuejs.org/v2/cookbook/editable-svg-icons.html)
- [Create a CMS-Powered Blog](https://vuejs.org/v2/cookbook/serverless-blog.html)
- [Unit Testing Vue Components](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html)
- [Creating Custom Scroll Directives](https://vuejs.org/v2/cookbook/creating-custom-scroll-directives.html)
- [Using Axios to Consume APIs](https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html)

## 貢献した際の特典
Vue.js 日本語公式サイトの[貢献ページ](https://jp.vuejs.org/contribution/)に、あなたの GitHub アカウントがクレジットとして掲載されます。

## 貢献方法
1. 翻訳したい方は、[プロジェクト](https://github.com/vuejs/jp.vuejs.org/projects/3)のBacklogにあるissue内で、「翻訳やります！」的なコメントで宣言してください :raising_hand:
1. @kazupon @re-fort @potato4d のうち1名に同 issue でコメントで承認されたら、正式に自分が選んだ issue の翻訳担当者としてアサインされたことになります
1. 翻訳を行います :fire: 今回が初翻訳ということであれば、[こちら](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md)をご一読ください
1. 翻訳終了後、プルリクエストを `vuejs/jp.vuejs.org` の `lang-ja` ブランチに送ります
1. レビュー :eyes: で指摘事項があったら修正し、再度 Push します :pencil:
1. レビュー :eyes: で OK ならば、マージされ、担当した翻訳は晴れて終了になります! :tada:

## 翻訳における注意事項
- 翻訳の締切は OSS なので特に設けませんが、作業開始してレビュー完了まで含めて**だいたい 1 ヶ月以内ぐらいを目処**に進めて頂けると助かります :blush:
- Cookbook ですがまだ beta なので変更される可能性が大いにあります。手間になりますが、**PRマージ前**に担当のセクションが更新された場合には、**取り込んで翻訳も追従**していただけると助かります :bow:
- 訳に不安がある場合などは、WIP(Work In Progress:作業中)な状態でプルリクエストを送り、区切りがよいセクション単位(段落)等で、適宜コミットしてその都度 Push して頂けると、レビュー :eyes: もしやすく、翻訳される方も気分的に楽になると思いますので、して頂けると助かります :pray:
- 翻訳作業を開始する際は、翻訳開始する際に、なるべく `lang-ja` ブランチの最新をものを使用してください。`lang-ja` は随時本家の最新内容を取り入れており、翻訳漏れが少なくなります
- 翻訳作業中に翻訳について不明点がある場合は、自分が翻訳宣言した issue にコメントお願いします :speech_balloon:

**Comment by re-fort** [comment]
@nicedchy @k-okina @potato4d @hisako135 @hikimon @ykhirao @pipopotamasu @masaakikunsan
/cc @kazupon 
 
みなさん、今回は翻訳表明ありがとうございます！
素晴らしい速度で各セクションの担当者が決定しました:tada:

担当分の翻訳はもう着手していただいて構いません:blush:
遅くとも**4月末**には全セクションが公開済みにできれば、と思っていますので、本業との兼ね合いで難しくなるようであれば教えていただければと思います。
また、注意書きにも記載しましたが、原文に更新があった場合には、関連 Issueに該当のIssueを貼りますので、そちらの内容も訳に取り込んでいただければと思います:pray:

今後、このissueでは、用語の統一などの各種連絡に使用しようと思います。
各担当間で連絡をしたいなどがもしあれば、このissueをお使いください。

それではお願いします！

**Comment by re-fort** [comment]
各cookbookに出てくる`Alternative Patterns`は`代替パターン`で統一お願いします！

**Comment by re-fort** [comment]
@nicedchy @k-okina @hisako135 @hikimon @ykhirao @masaakikunsan
/cc @kazupon @potato4d

textlintの対象にcookbookが含まれていなかったため、cookbookをlintの対象に入れる修正を行っています。
お手数ですが、PR作成時は`lang-ja`ブランチをmergeした上で、lintが通ることを確認お願いします:pray:

**Comment by re-fort** [comment]
@nicedchy @k-okina @hisako135 @hikimon @ykhirao @masaakikunsan @c-su 
/cc @kazupon @potato4d
みなさんの協力のおかげでCookbookの各コンテンツが翻訳完了という状態になりました:tada:
ご協力いただきありがとうございました:blush:

最近、またひとつcookbookが追加されたので、余力がある方はぜひご協力おねがいします！
https://github.com/vuejs/jp.vuejs.org/issues/972

**Comment by kazupon** [comment]
@nicedchy @k-okina @hisako135 @hikimon @ykhirao @masaakikunsan @c-su
みなさん、翻訳ありがとうございました！

@re-fort @potato4d
取りまとめ、レビュー、おつかれさまでした！

メインメンテナーとして、改めまして、
みなさんのご協力によりクックブックの翻訳作業終えることができたことに感謝いたします！
