### ISSUE TITLE
[Cookbook]: Introductionの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#815]
## 原文
https://vuejs.org/v2/cookbook/index.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/index.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)
#843

**Comment by re-fort** [comment]
担当します :raising_hand:
(他にやりたい方いたらお願いしたいので、コメントください)

**Comment by nicedaichi3** [comment]
自分やっても大丈夫でしょうか？

**Comment by re-fort** [comment]
助かります！
ぜひお願いします！

**Comment by nicedaichi3** [comment]
週明けPR出します！
宜しくお願いします 🙇

**Comment by nicedaichi3** [comment]
@re-fort 
ご連絡遅くなってしまってすいません 🙇 
明日PR出させていただきます
初翻訳なので、少し口語的になってしまっている点多いと思いますがご指摘のほどよろしくお願いします。
