### ISSUE TITLE
[Cookbook]: Adding Instance Propertiesの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#816]
## 原文
https://vuejs.org/v2/cookbook/adding-instance-properties.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/adding-instance-properties.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)
#842 
#843 
#865

**Comment by kahirokunn** [comment]
翻訳やります！

**Comment by re-fort** [comment]
お願いします:+1:

**Comment by kahirokunn** [comment]
はい！頑張ります！
よろしくお願いします！

**Comment by kahirokunn** [comment]
現在翻訳着手中です。

**Comment by kahirokunn** [comment]
@re-fort 
こちら一旦翻訳完了しました。
#890 
コメントもしたので、レビューお願いします！

**Comment by kahirokunn** [comment]
初めての翻訳作業ですので、色々と指摘頂けたらと思います！
