### ISSUE TITLE
[Cookbook]: Editable SVG Icon Systemsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#818]
## 原文
https://vuejs.org/v2/cookbook/editable-svg-icons.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/editable-svg-icons.md

**Comment by hisako135** [comment]
翻訳やりたいです！

**Comment by re-fort** [comment]
お願いします:+1:
