### ISSUE TITLE
[Cookbook]: Create a CMS-Powered Blogの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#819]
## 原文
https://vuejs.org/v2/cookbook/serverless-blog.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/serverless-blog.md

**Comment by hikimon** [comment]
ここ対応してもよいでしょうか？？

**Comment by re-fort** [comment]
はい！お願いします:+1:

**Comment by hikimon** [comment]
ありがとうございます！mm

**Comment by hikimon** [comment]
大変遅くなりましたが、PRを送りました。
https://github.com/vuejs/jp.vuejs.org/pull/917
ご確認よろしくお願いいたします！
