### ISSUE TITLE
[Cookbook]: Unit Testing Vue Componentsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#822]
## 原文
https://vuejs.org/v2/cookbook/unit-testing-vue-components.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/unit-testing-vue-components.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)
#843 
#889

**Comment by ykhirao** [comment]
翻訳やりたいです 🙋

**Comment by re-fort** [comment]
お願いします:+1:
