### ISSUE TITLE
[Cookbook]: Creating Custom Scroll Directivesの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#823]
## 原文
https://vuejs.org/v2/cookbook/creating-custom-scroll-directives.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/creating-custom-scroll-directives.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)
#843

**Comment by pipopotamasu** [comment]
翻訳やります！
Vue.js関連の翻訳は初めてですがやらせていただきたいです。

**Comment by re-fort** [comment]
お願いします:+1:

**Comment by pipopotamasu** [comment]
明日から着手します。

**Comment by pipopotamasu** [comment]
こちら一旦翻訳完了しました。
https://github.com/vuejs/jp.vuejs.org/pull/859

うまく翻訳できていない箇所もあり、コメントしているのでレビューお願いします(コメント以外の箇所も見ていただけると助かります)。

**Comment by re-fort** [comment]
ref: #859
