### ISSUE TITLE
[Cookbook]: Using Axios to Consume APIsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#824]
## 原文
https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/using-axios-to-consume-apis.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)
#843 
#858

**Comment by masaakikunsan** [comment]
翻訳やります！

**Comment by re-fort** [comment]
お願いします:+1:

**Comment by masaakikunsan** [comment]
着手今週の日曜日になりそうです

**Comment by masaakikunsan** [comment]
こちら遅れていてすみません
今日夜残り着手してPRだします
