### ISSUE TITLE
[Cookbook]: Debugging in VS Code and Chromeの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#846]
## 原文
https://vuejs.org/v2/cookbook/debugging-in-vscode.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/debugging-in-vscode.md

## 関連 Issue(翻訳を表明されてから原文が変更された際はこちらに記入します)

**Comment by c-su** [comment]
翻訳させていただけるとうれしいですm(_ _)m

**Comment by re-fort** [comment]
@c-su お願いします！

**Comment by re-fort** [comment]
@c-su こちら進捗いかがでしょうか？

**Comment by c-su** [comment]
@re-fort 
遅れて申し訳ありません。着手はしておりますので、週末入るまでにはPR出しますｍｍ
