### ISSUE TITLE
[Components In-Depth]: Component Registrationの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#918]
## 原文
https://vuejs.org/v2/guide/components-registration.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-registration.md

**Comment by RyoNkmr** [comment]
こちら、翻訳したいです！

**Comment by re-fort** [comment]
@RyoNkmr お願いします！

**Comment by corosukeK** [comment]
原文のリンク間違えてますよー
誤
https://vuejs.org/v2/cookbook/debugging-in-vscode.html
正
https://vuejs.org/v2/guide/components-registration.html

**Comment by re-fort** [comment]
@corosukeK ありがとうございます！修正しました！
