### ISSUE TITLE
[Components In-Depth]: Propsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#919]
## 原文
https://vuejs.org/v2/guide/components-props.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-props.md

**Comment by sa2cie** [comment]
やりたいです！

**Comment by re-fort** [comment]
@vvaka1122 ぜひおねがいします！

**Comment by kazupon** [comment]
@vvaka1122 こちらは、どんな感じでしょうか？

**Comment by kazupon** [comment]
@vvaka1122 
上記コメントから5日立ちましたが、レスがないので、翻訳難しそうと判断して、一旦assignからはずさせていただきたいと思います。
翻訳挙手ありがとうございました！

**Comment by kazupon** [comment]
引き続き募集していますので、興味がある方は、コメントで🙋お願いします！

**Comment by potato4d** [comment]
@kazupon 

今日中あたりをめどでもし翻訳希望者つかなければ、そろそろローカライズを待っている人もいそうなので私のほうで翻訳進めてしまおうかなーと思っています。

**Comment by kazupon** [comment]
@potato4d 
では、お願いできますか？

**Comment by potato4d** [comment]
@kazupon 
🙆 作業時間一週間程度みておいていただけると

**Comment by kazupon** [comment]
@potato4d 
いつもありがとうございます！ 🙏 
では、よろしくおねがいします！

**Comment by potato4d** [comment]
連絡遅くなりました 🙇 
本日完了予定です
