### ISSUE TITLE
[Components In-Depth]: Custom Eventsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#920]
## 原文
https://vuejs.org/v2/guide/components-custom-events.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-custom-events.md

**Comment by moksahero** [comment]
こちら翻訳させていただければ！

**Comment by re-fort** [comment]
@moksahero おねがいします！

**Comment by moksahero** [comment]
いったん翻訳してPR飛ばしてみました。https://github.com/vuejs/jp.vuejs.org/pull/935/

**Comment by re-fort** [comment]
ref: #935
