### ISSUE TITLE
[Components In-Depth]: Slotsの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#921]
## 原文
https://vuejs.org/v2/guide/components-slots.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-slots.md

**Comment by resessh** [comment]
これやりたいです！

**Comment by re-fort** [comment]
@resessh おねがいします！
