### ISSUE TITLE
[Components In-Depth]: Handling Edge Casesの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#923]
## 原文
https://vuejs.org/v2/guide/components-edge-cases.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-edge-cases.md

**Comment by pipopotamasu** [comment]
これやりたいです！
期限とかってありますか?

**Comment by re-fort** [comment]
@pipopotamasu おねがいします！期限については検討後に回答します！

**Comment by re-fort** [comment]
@pipopotamasu 期限は特に設けませんが、5月内に公開まで持っていけると嬉しいです！

**Comment by pipopotamasu** [comment]
@re-fort 承知しました！

**Comment by resessh** [comment]
https://github.com/vuejs/jp.vuejs.org/pull/1011 こちらでdoneしてるのでcloseして良いかと〜

**Comment by kazupon** [comment]
@resessh ありがとうございます！忘れてました。。。
