### ISSUE TITLE
[Cookbook]: Avoiding Memory Leaksの翻訳

### ISSUE THREAD

**Issue by re-fort** [vuejs/jp.vuejs.org#972]
## 原文
https://vuejs.org/v2/cookbook/avoiding-memory-leaks.html

## 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/cookbook/avoiding-memory-leaks.md

**Comment by nicedaichi3** [comment]
@re-fort 
こちらやってもいいですか？

**Comment by re-fort** [comment]
@nicedchy おねがいします！

**Comment by kazupon** [comment]
close #984
